name = "redirectiontool"
main = "src/index.ts"
compatibility_date = "2023-04-11"

kv_namespaces = [
  { binding = "redirectiontool", id = "{{ CF_KV_NAMESPACE }}", preview_id = "{{ CF_KV_PREVIEW_NAMESPACE }}" }
]
