name = "cdn-redirect"
main = "src/index.ts"
compatibility_date = "2023-04-11"

kv_namespaces = [
  { binding = "redirects-kv", id = "{{ CF_KV_NAMESPACE }}", preview_id = "{{ CF_KV_PREVIEW_NAMESPACE }}" }
]

[vars]
CREATE_API_KEY = "{{ CREATE_API_KEY }}"
