name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0

      - name: Install dependencies
        run: npm install

      - name: Generate Wrangler config
        run: npm run config

      - name: Install Wrangler globally
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Workers
        run: wrangler deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_KV_NAMESPACE: ${{ secrets.CF_KV_NAMESPACE }}
          CF_KV_PREVIEW_NAMESPACE: ${{ secrets.CF_KV_PREVIEW_NAMESPACE }}
          CREATE_API_KEY: ${{ secrets.CREATE_API_KEY }}
