name: Build and Deploy

on:
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main         # Trigger on push to main branch
  pull_request:
    branches:
      - main         # Trigger on PRs targeting main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0

      - name: Install dependencies
        run: npm install

      - name: Deploy using Wrangler
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            npm run config    # Prepares wrangler.toml
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_KV_NAMESPACE: ${{ secrets.CF_KV_NAMESPACE }}
